apiVersion: apps/v1
kind: Deployment
metadata:
  name: cce21days-app3-huyong5802
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cce21days-app3-huyong5802
  template:
    metadata:
      labels:
        app: cce21days-app3-huyong5802
    spec:
      containers:
        - name: container-0
          image: 'redis:latest'
      imagePullSecrets:
        - name: default-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - 192.168.0.148
