apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appgroup: ''
  name: cce21days-app2-huyong5802
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cce21days-app2-huyong5802
  template:
    metadata:
      labels:
        app: cce21days-app2-huyong5802
    spec:
      containers:
        - name: container-0
          image: '100.125.0.198:20202/f00355482/tanks:v1'
      imagePullSecrets:
        - name: default-secret
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cce21days-app1-huyong5802
              topologyKey: kubernetes.io/hostname
