apiVersion: v1
kind: Pod
metadata:
  name: cce21days-huyong5802
  labels:
    app: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.0.148
  containers:
  - image: 100.125.0.198:20202/f00355482/tanks:v1 #容器镜像地址
    imagePullPolicy: IfNotPresent
    name: container-0
    resources: {}
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-secret
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
